#pragma once

// Reward type
#define REWARD_TYPE_SIGNUP 1
#define REWARD_TYPE_CONTENTS 2
#define REWARD_TYPE_MAX 3

// Reward status
#define REWARD_STATUS_RESERVE 0
#define REWARD_STATUS_USE 1
#define REWARD_STATUS_CLOSE 2

#define ERROR_MSG_INVALID_REWARD_AMOUNT "{\"CODE\":\"0201\",\"MSG\":\"ERROR_MSG_INVALID_REWARD_AMOUNT\"}"
#define ERROR_MSG_REWARD_NOT_EXIST "{\"CODE\":\"0202\",\"MSG\":\"ERROR_MSG_REWARD_NOT_EXIST\"}"
#define ERROR_MSG_INVALID_REWARD_TYPE "{\"CODE\":\"0202\",\"MSG\":\"ERROR_MSG_INVALID_REWARD_TYPE\"}"
#define ERROR_MSG_INVALID_REWARD_TOKEN "{\"CODE\":\"0202\",\"MSG\":\"ERROR_MSG_INVALID_REWARD_TOKEN\"}"





