#pragma once

// Reward type
#define REWARD_TYPE_SIGNUP 1
#define REWARD_TYPE_CONTENTS 2
#define REWARD_TYPE_MAX 3

// Reward status
#define REWARD_STATUS_RESERVE 0
#define REWARD_STATUS_USE 1
#define REWARD_STATUS_CLOSE 2

// max Reward name length
#define REWARD_MAX_NAME_LEN 50


#define ERROR_MSG_INVALID_REWARD_AMOUNT "{\"CODE\":\"0201\",\"MSG\":\"ERROR_MSG_INVALID_REWARD_AMOUNT\"}"
#define ERROR_MSG_REWARD_NOT_EXIST "{\"CODE\":\"0202\",\"MSG\":\"ERROR_MSG_REWARD_NOT_EXIST\"}"
#define ERROR_MSG_INVALID_REWARD_TYPE "{\"CODE\":\"0203\",\"MSG\":\"ERROR_MSG_INVALID_REWARD_TYPE\"}"
#define ERROR_MSG_INVALID_REWARD_TOKEN "{\"CODE\":\"0204\",\"MSG\":\"ERROR_MSG_INVALID_REWARD_TOKEN\"}"
#define ERROR_MSG_MAX_REWARD_NAME "{\"CODE\":\"0205\",\"MSG\":\"ERROR_MSG_MAX_REWARD_NAME\"}"




