#pragma once

#define CAPSULE_MAX_DATA_LEN 200

// Erorr code
#define CAPSULE_ERROR_MSG_ALREADY_EXIST_SEQ "{\"CODE\":\"0101\":,\"MSG\":\"CAPSULE_ERROR_MSG_ALREADY_EXIST_SEQ \"}"
#define CAPSULE_ERROR_MSG_NOT_EXIST_SEQ "{\"CODE\":\"0102\":,\"MSG\":\"CAPSULE_ERROR_MSG_NOT_EXIST_SEQ\"}"
#define CAPSULE_ERROR_MSG_ALREADY_END "{\"CODE\":\"0103\":,\"MSG\":\"CAPSULE_ERROR_MSG_ALREADY_END \"}"
#define CAPSULE_ERROR_MSG_NO_FIND_SEQ "{\"CODE\":\"0104\":,\"MSG\":\"CAPSULE_ERROR_MSG_NO_FIND_SEQ\"}"
#define CAPSULE_ERROR_MSG_OVER_MAX_DATA_LEN "{\"CODE\":\"0105\":,\"MSG\":\"CAPSULE_ERROR_MSG_OVER_MAX_DATA_LEN\"}"
